### ISSUE TITLE
.mcfx file support

### ISSUE THREAD

**Issue by cweiske** [bash0/cewe2pdf#119]
A friend sent me a cewe file that contained all data in a single file with extension `.mcxf`.
It is a sqlite3 file that has only one table `Files`.

The structure:
```
$ sqlite3 photobook.mcfx '.schema Files'
CREATE TABLE Files(Filename TEXT PRIMARY KEY,Data BLOB,LastModified INTEGER);
```

Extracting all files is possible on the shell with the following command:
```
for filename in $(sqlite3 photobook.mcfx 'select Filename from Files'); do sqlite3 photobook.mcfx "select writefile(Filename, Data) from Files where Filename='$filename'"; done
```

Then we have a `data.mcf` file and all the images.

Looks like an official archive/export format.

Maybe the README could talk about it, or the script could get full support by first extracting those files.

**Comment by michaelKle** [comment]
I have just tried this and it mostly works. However, filenames with spaces are not correctly exported.

With an adapted command I do get all files:
`OFS="$IFS"; IFS=$'\n'; for filename in $(sqlite3 Photobook.mcfx 'select Filename from Files'); do sqlite3 Photobook.mcfx "select writefile(Filename, Data) from Files where Filename='$filename'"; done; IFS="$OIFS"`

**Comment by AnEnglishmanInNorway** [comment]
7.3.4 just arrived from my CEWE franchise here in Norway, with the new mcfx format. I started with a test album and let it save as .mcfx, so I could try the export with sqlite3 described here.
The first problem is that I run on a Windows 10 (Pro) machine! It's a long time since I worked actively with any version of Unix, let alone from within Windows, but since I last tried it seems that Microsoft have massively improved their WSL (Windows Subsystem for Linux) setup. Getting an Ubuntu subsystem up and running was surprisingly easy, see [here](https://learn.microsoft.com/en-gb/windows/wsl/install). Worth knowing, if any of the other readers here also use Windows.
When I tried the first sqlite3 command it very cleverly pointed out that sqlite was not installed, and told me how to do that, and from there the export as shown by @michaelKle worked fine. 
RIght now I'm stuck because the new 7.3.4 version doesn't seem to have a cliparts_default.xml file, and that blows away any hope of getting cliparts etc working. I'll report back on that.

**Comment by AnEnglishmanInNorway** [comment]
Another comment in relation to the mcfx format and what we might do with it. I agree with @cweiske that the most likely "simple" solution would be for our code to recognize the new format and extract all the files to some temporary location for processing by our (presumably) largely unaltered existing code. I had a quick look around to see how that might be done, and found a good article [here](https://www.sql-easy.com/learn/how-to-use-sql-in-python/). The article says that Python has native support for SQLite using sqlite3, so it surely can't be that difficult for us to build in the sql statements earlier in this conversation. Something to keep somebody amused one day...

**Comment by cweiske** [comment]
Great!

**Comment by cweiske** [comment]
Not unpacking the .mcfx file would be even better :) For that we'd need to switch to [fsspec](https://filesystem-spec.readthedocs.io/en/latest/index.html) for file operations and implement our own adapter: https://filesystem-spec.readthedocs.io/en/latest/developer.html#implementing-a-backend

Just a thought. Maybe I'll implement it.
