### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '.mcf'

### ISSUE THREAD

**Issue by anto1ne** [bash0/cewe2pdf#156]
Hi 

Thank you for this script, it is really great :-)

I have a small issue but I am not really sure if it is a bug in your software or an error on my side

I installed your software and it works really well.

I can run it in any directory except in my home directory and I do not know why.

```
antoine@talos:~$ python3 /home/antoine/Apps/cewe2pdf/cewe2pdf.py
WARNING:root:No module named 'pillow_heif': direct use of .heic images is not available
Traceback (most recent call last):
  File "/home/antoine/Apps/cewe2pdf/cewe2pdf.py", line 1743, in <module>
    resultFlag = convertMcf(args.inputFile, args.keepDoublePages, pageNumbers, mcfxTmpDir, appDataDir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/Apps/cewe2pdf/cewe2pdf.py", line 1195, in convertMcf
    mcffile = open(mcfxmlname, 'rb')
              ^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '.mcf'
antoine@talos:~$ cd Bureau/
antoine@talos:~/Bureau$ python3 /home/antoine/Apps/cewe2pdf/cewe2pdf.py
WARNING:root:No module named 'pillow_heif': direct use of .heic images is not available
usage: cewe2pdf.py [-h] [--keepDoublePages] [--pages PAGES]
                   [--tmp-dir MCFXTMPDIR] [--appdata-dir APPDATADIR]
                   [inputFile]

Convert a photo-book from .mcf/.mcfx file format to .pdf

positional arguments:
  inputFile             the mcf input file. If not given, the first .mcf/.mcfx
                        in the current directory is used. (default: None)

options:
  -h, --help            show this help message and exit
  --keepDoublePages     Each page in the .pdf will be a double-sided page,
                        instead of a normal single page. (default: False)
  --pages PAGES         Page numbers to render, e.g. 1,2,4-9 (default: None)
  --tmp-dir MCFXTMPDIR  Directory for .mcfx file extraction (default: None)
  --appdata-dir APPDATADIR
                        Directory for persistent app data, eg ttf fonts
                        converted from otf fonts (default: None)

Example:
   python cewe2pdf.py c:\path\to\my\files\my_nice_fotobook.mcf
antoine@talos:~/Bureau$ 
```

Note that when a mcf is in my home directory, I do not have an error.

**Comment by AnEnglishmanInNorway** [comment]
Hi! I'm away from my development computer for a few weeks but unless you
find the problem before then I'll take a quick look when I get back.

It could be there's a check missing in the newly added mcf/mcfx handling
for the case where no album file is specified. Another thought is that Cewe
might save personal settings in a .mcf directory in the home directory on
Linux. I use Windows so I can't check that myself. Perhaps you could check?

**Comment by anto1ne** [comment]
Hi

do not worry, this is not an emergency :)

yes I think that Cewe creates a .mcf directory in the home directory on Linux

```
antoine@talos:~$ ls -d .m*
.mcf  .mozilla
antoine@talos:~$
```

if you need help, I can perform few test, just tell me what you need, I will give it a try.

I think that you are going in the right direction.
When I create a .mcf directory in another directory, cewe2pdf fails in that directory

```
antoine@talos:~/Bureau$ cewe2pdf 
WARNING:root:No module named 'pillow_heif': direct use of .heic images is not available
usage: cewe2pdf.py [-h] [--keepDoublePages] [--pages PAGES]
                   [--tmp-dir MCFXTMPDIR] [--appdata-dir APPDATADIR]
                   [inputFile]

Convert a photo-book from .mcf/.mcfx file format to .pdf

positional arguments:
  inputFile             the mcf input file. If not given, the first .mcf/.mcfx
                        in the current directory is used. (default: None)

options:
  -h, --help            show this help message and exit
  --keepDoublePages     Each page in the .pdf will be a double-sided page,
                        instead of a normal single page. (default: False)
  --pages PAGES         Page numbers to render, e.g. 1,2,4-9 (default: None)
  --tmp-dir MCFXTMPDIR  Directory for .mcfx file extraction (default: None)
  --appdata-dir APPDATADIR
                        Directory for persistent app data, eg ttf fonts
                        converted from otf fonts (default: None)

Example:
   python cewe2pdf.py c:\path\to\my\files\my_nice_fotobook.mcf
antoine@talos:~/Bureau$ mkdir .mcf
antoine@talos:~/Bureau$ cewe2pdf 
WARNING:root:No module named 'pillow_heif': direct use of .heic images is not available
Traceback (most recent call last):
  File "/home/antoine/Apps/cewe2pdf/cewe2pdf.py", line 1743, in <module>
    resultFlag = convertMcf(args.inputFile, args.keepDoublePages, pageNumbers, mcfxTmpDir, appDataDir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/Apps/cewe2pdf/cewe2pdf.py", line 1195, in convertMcf
    mcffile = open(mcfxmlname, 'rb')
              ^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '.mcf'
antoine@talos:~/Bureau$
```

**Comment by AnEnglishmanInNorway** [comment]
Hi! Had 5 mins to spare and had a quick look at the code on my phone. If you don't specify the name of an mcf or mcfx on the command line (as you don't when you are just trying to see the usage message) then the program will try to locate the first album file in the current directory and process that! 
That's on line 1702 in the code I'm looking at:
`fnames = [i for i in os.listdir('.') if i.endswith('.mcf') or i.endswith('.mcfx')]
`
A very trivial fix to avoid processing the .mcf directory might be to avoid a name which is only .mcf, like this:
`fnames = [i for i in os.listdir('.') if not i == ".mcf" and (i.endswith('.mcf') or i.endswith('.mcfx'))]
`
Personally I don't like the idea that when there is no album specified then the program will by default process the first album it finds in a directory. My preferred solution would be to remove that capability completely, so that it was mandatory to specify the name of the album to be used. I don't know if anybody else has strong feelings on the subject, before we make any change to the common base code?

**Comment by anto1ne** [comment]
> My preferred solution would be to remove that capability completely, so that it was mandatory to specify the name of the album to be used

I agree with you about this

**Comment by AnEnglishmanInNorway** [comment]
The code history here suggests that @BarchSteel was probably the one who made the code process the first album file in the directory, in December 2019.  Perhaps because he conventionally only has one album in a directory? Then the idea would make perfect sense. Perhaps you have a comment here, before I change the behaviour so that providing an mcf or mcfx name is mandatory?

**Comment by anto1ne** [comment]
I am a new cewe2pdf user so my point of view is maybe not the best.
In my case, I store all my mcfx file in the same directory, so providing an mcfx name should mandatory

**Comment by AnEnglishmanInNorway** [comment]
Not many comments here.
I propose to change the command line interface so that it is mandatory to specify a single .mcf(x) file. 
If a filename is not specified, then the help text will be shown.
If the current directory contains just a single .mcf(x), then it will be shown as an example in the help text.
