### ISSUE TITLE
F821 undefined name 'keyAccountFileName'

### ISSUE THREAD

**Issue by cweiske** [bash0/cewe2pdf#91]
There is an error:
```
./cewe2pdf.py:1028:80: F821 undefined name 'keyAccountFileName'
        print('Could not extract keyAccount tag in file: {}, reason {}'.format(keyAccountFileName, ex))
                                                                               ^
1     F821 undefined name 'keyAccountFileName'
```

From https://github.com/bash0/cewe2pdf/runs/3130861787

Maybe catching the exception is not necessary anymore.

**Comment by AnEnglishmanInNorway** [comment]
I think I need help here, Christian, if you could be bothered?
I have a commit 704d0e1a (704d0e1a4cbe74b8ddc4260a0ee08b8a521fc27c) which fixes this errore, but I can't get it merged down to bash0/master. When I create a pull request, it says it cannot merge because of conflicts - which I don't think exist. I suspect it is confused by the fact that I squashed some of your commits up to my master before I saw the comment about not using squash, and then reverted the squash so I could use rebase. 
The message about not being able to automatically merge suggested a series of command line operations which I tried but with no success.

**Comment by cweiske** [comment]
Reset your local master to the bash0 version.

First, make a backup (unless you're already in a separate branch):
```
git checkout -b myoldmaster
```

Now reset:

```
git fetch bash0
git checkout master
git reset --hard bash0/master
```

Now apply your patch (last commit of the myoldmaster branch:
```
git cherry-pick myoldmaster
```

**Comment by AnEnglishmanInNorway** [comment]
Thanks! The commands seemed to work (though I had to use the name "upstream" rather than "bash0"  to avoid a complaint that bash0 was not a repository. But ... I'm still not there. Take a look at https://github.com/bash0/cewe2pdf/pull/93.

**Comment by cweiske** [comment]
I personally use rebases more than merges because it keeps the history clean.

You currently have unnecessary merge commits like "Merge branch 'bash0:master' into master".
This can be prevented with the commands above, or:

```
git fetch bash0
git rebase bash0/master
```

This uses bash0's master branch as base, and applies all the commits missing in bash0's branch on top of it.

**Comment by cweiske** [comment]
Note: You need to force-push your branch then! git push -f
